spring.application.name=harvestiq

spring.datasource.url=jdbc:h2:mem:harvestiq
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

harvestiq.admin.password=${HARVESTIQ_ADMIN_PASSWORD}
harvestiq.staff.password=${HARVESTIQ_STAFF_PASSWORD}